package com.example.foodhall.datamodel

data class VendorTypeDetail(
    val app_image: String?,
    val app_thumbnail: String?,
    val best_known_for: String?,
    val classification: String?,
    val cover_image: String?,
    val cuisine_ids: String?,
    val cuisines: String?,
    val description: String?,
    val fssai_details: String?,
    val gift_wrap_price: String?,
    val guid: String?,
    val id: String?,
    val image: String?,
    val is_featured: String?,
    val is_gift_wrap: String?,
    val is_taxable: String?,
    val latitude: String?,
    val locality_id: String?,
    val locality_name: String?,
    val longitude: String?,
    val meal_time_id: String?,
    val name: String?,
    val newly_order_min_time: Int,
    val offer_for_vendor: String?,
    val offer_lists: Any?,
    val openingTime: List<OpeningTime>,
    val order_min_time: Int,
    val order_min_value: String?,
    val priority: String?,
    val rating: String?,
    val spotlight_app_image: String?,
    val summary: String?,
    val vendor_type_id: String?,
    val vendor_type_name: String?
)
data class OpeningTime(var start : String ?= "", var end : String ?= "")